language: c

compiler: gcc

# The EDU plan doesn't support sudo :(

#before_install:
#    - sudo apt-get update -qq
#    - apt-get install -y cppcheck

script:
#    - cppcheck --enable=warning,style,performance,portability,missingInclude --std=c89 *.c -q
    - make
